spring:
  devtools:
    restart:
      enabled: true 
      exclude: "static/**, public/**"
      additional-exclude: "**/*.xml" 
      additional-paths: ['src/main/webapp', 'src/main/resources']
      trigger-file: .reload
      
server:
   port: 1234
   

greeting:
   app: custom
