version: '3'
services:
  node:
    build: 
      context: ./src/main/docker/node
      dockerfile: Dockerfile
    ports:
      # for angular cli
      - "4200:4200"
      # for firebase cli
      - "9005:9005"
      # for Web app
      - "80:80"
      - "8080:8080"
      - "8888:8888"
    volumes:
      - ".:/home/node/app"
    working_dir: /home/node/app/src/main/web
    # user: "1000:1000"
    user: "${USER_ID}:${GROUP_ID}"

    tty: true