version: '3'

services:
    gradle:
        image: "gradle:6.1.1-jdk11"
        working_dir: /home/gradle/project
        volumes:
            # working_dirに合わせる。
            # ../default.gradleがあるため一階層上をマウントする
            - "..:/home/gradle/project"
        command: >
            sh -c "cd TrialWeb &&
            gradle build"
