version: '3'

services:
    node:
        image: "node:12.16.0-alpine3.11"
        working_dir: /home/node/app
        volumes:
            - ".:/home/node/app"
        #tty: true
        command: >
            sh -c "echo '--modules-folder WebContent/lib_node' > .yarnrc &&
            yarn install"
